# Generated by Django 4.2.7 on 2025-07-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotationtemplate",
            name="color_scheme",
            field=models.CharField(blank=True, default="#1976d2", max_length=32),
        ),
        migrations.AddField(
            model_name="quotationtemplate",
            name="footer_notes",
            field=models.TextField(blank=True),
        ),
    ]
