# Generated by Django 4.2.7 on 2025-07-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotations", "0002_quotationtemplate_color_scheme_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotation",
            name="header_custom_fields",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
