# Generated by Django 4.2.7 on 2025-07-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotations", "0003_quotation_header_custom_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotationtemplate",
            name="header_fields_config",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
