# Generated by Django 4.2.7 on 2025-07-25 14:21

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ("quotations", "0004_quotationtemplate_header_fields_config"),
        ("clients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Rename QuotationTemplate fields
        migrations.RenameField(
            model_name="quotationtemplate",
            old_name="company",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="quotationtemplate",
            old_name="created_by",
            new_name="user",
        ),
        
        # Add new fields to QuotationTemplate
        migrations.AddField(
            model_name="quotationtemplate",
            name="description",
            field=models.TextField(blank=True, help_text="Description of this template"),
        ),
        migrations.AddField(
            model_name="quotationtemplate",
            name="primary_color",
            field=models.CharField(default="#1976d2", help_text="Primary color (hex code)", max_length=7),
        ),
        migrations.AddField(
            model_name="quotationtemplate",
            name="secondary_color",
            field=models.CharField(default="#f8f9fa", help_text="Secondary color (hex code)", max_length=7),
        ),
        migrations.AddField(
            model_name="quotationtemplate",
            name="text_color",
            field=models.CharField(default="#333333", help_text="Text color (hex code)", max_length=7),
        ),
        migrations.AddField(
            model_name="quotationtemplate",
            name="accent_color",
            field=models.CharField(default="#e9ecef", help_text="Accent color for borders and highlights (hex code)", max_length=7),
        ),
        migrations.AddField(
            model_name="quotationtemplate",
            name="show_company_logo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="quotationtemplate",
            name="show_company_details",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="quotationtemplate",
            name="show_bank_details",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="quotationtemplate",
            name="show_signature",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="quotationtemplate",
            name="document_title",
            field=models.CharField(default="QUOTATION", help_text="Document title to display", max_length=100),
        ),
        migrations.AddField(
            model_name="quotationtemplate",
            name="number_prefix",
            field=models.CharField(default="QT", help_text="Quotation number prefix", max_length=10),
        ),
        migrations.AddField(
            model_name="quotationtemplate",
            name="default_terms",
            field=models.TextField(blank=True, default="This quotation is valid for 30 days from the date of issue", help_text="Default terms for new quotations"),
        ),
        migrations.AddField(
            model_name="quotationtemplate",
            name="footer_text",
            field=models.TextField(blank=True, help_text="Footer text to display on quotations"),
        ),
        migrations.AddField(
            model_name="quotationtemplate",
            name="is_default",
            field=models.BooleanField(default=False, help_text="Use as default template"),
        ),
        
        # Rename Quotation fields
        migrations.RenameField(
            model_name="quotation",
            old_name="number",
            new_name="quotation_number",
        ),
        migrations.RenameField(
            model_name="quotation",
            old_name="date",
            new_name="quotation_date",
        ),
        migrations.RenameField(
            model_name="quotation",
            old_name="tax",
            new_name="total_tax",
        ),
        migrations.RenameField(
            model_name="quotation",
            old_name="discount",
            new_name="total_discount",
        ),
        migrations.RenameField(
            model_name="quotation",
            old_name="shipping",
            new_name="shipping_fee",
        ),
        migrations.RenameField(
            model_name="quotation",
            old_name="total",
            new_name="grand_total",
        ),
        migrations.RenameField(
            model_name="quotation",
            old_name="company",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="quotation",
            old_name="created_by",
            new_name="user",
        ),
        
        # Add new fields to Quotation
        migrations.AddField(
            model_name="quotation",
            name="valid_until",
            field=models.DateField(blank=True, help_text="Quotation validity period", null=True),
        ),
        migrations.AddField(
            model_name="quotation",
            name="other_charges",
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="quotation",
            name="subtotal",
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        
        # Remove old fields from Quotation
        migrations.RemoveField(
            model_name="quotation",
            name="color_scheme",
        ),
        migrations.RemoveField(
            model_name="quotation",
            name="header_custom_fields",
        ),
        
        # Rename QuotationItem fields
        migrations.RenameField(
            model_name="quotationitem",
            old_name="total",
            new_name="line_total",
        ),
        
        # Add new fields to QuotationItem
        migrations.AddField(
            model_name="quotationitem",
            name="product_service",
            field=models.CharField(blank=True, help_text="Product or service name", max_length=250),
        ),
        
        # Update field attributes
        migrations.AlterField(
            model_name="quotation",
            name="quotation_number",
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="quotation_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="quotations", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="client",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="quotations", to="clients.client"),
        ),
        migrations.AlterField(
            model_name="quotationtemplate",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="quotation_templates", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="quotationitem",
            name="description",
            field=models.CharField(blank=True, help_text="Detailed description", max_length=500),
        ),
        migrations.AlterField(
            model_name="quotationitem",
            name="quantity",
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="quotationitem",
            name="unit_price",
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        
        # Add indexes
        migrations.AddIndex(
            model_name="quotation",
            index=models.Index(fields=["user", "-created_at"], name="quotations__user_id_created_at_idx"),
        ),
        migrations.AddIndex(
            model_name="quotation",
            index=models.Index(fields=["quotation_number"], name="quotations__quotation_number_idx"),
        ),
        migrations.AddIndex(
            model_name="quotation",
            index=models.Index(fields=["status"], name="quotations__status_idx"),
        ),
        migrations.AddIndex(
            model_name="quotation",
            index=models.Index(fields=["quotation_date"], name="quotations__quotation_date_idx"),
        ),
        migrations.AddIndex(
            model_name="quotation",
            index=models.Index(fields=["valid_until"], name="quotations__valid_until_idx"),
        ),
        migrations.AddIndex(
            model_name="quotation",
            index=models.Index(fields=["client"], name="quotations__client_id_idx"),
        ),
        
        # Add Meta options
        migrations.AlterModelOptions(
            name="quotation",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="quotationtemplate",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="quotationitem",
            options={"ordering": ["id"]},
        ),
        
        # Add unique constraints
        migrations.AlterUniqueTogether(
            name="quotationtemplate",
            unique_together={("user", "name")},
        ),
    ]
