# Generated by Django 4.2.7 on 2025-07-25 14:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotations", "0005_redesign_quotations_app"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="quotation",
            new_name="quotations__user_id_57ceb1_idx",
            old_name="quotations__user_id_created_at_idx",
        ),
        migrations.RenameIndex(
            model_name="quotation",
            new_name="quotations__quotati_d2f33a_idx",
            old_name="quotations__quotation_number_idx",
        ),
        migrations.RenameIndex(
            model_name="quotation",
            new_name="quotations__status_2435f4_idx",
            old_name="quotations__status_idx",
        ),
        migrations.RenameIndex(
            model_name="quotation",
            new_name="quotations__quotati_eaed53_idx",
            old_name="quotations__quotation_date_idx",
        ),
        migrations.RenameIndex(
            model_name="quotation",
            new_name="quotations__valid_u_5c5317_idx",
            old_name="quotations__valid_until_idx",
        ),
        migrations.RenameIndex(
            model_name="quotation",
            new_name="quotations__client__bb8ebd_idx",
            old_name="quotations__client_id_idx",
        ),
        migrations.RemoveField(
            model_name="quotationtemplate",
            name="branding",
        ),
        migrations.RemoveField(
            model_name="quotationtemplate",
            name="color_scheme",
        ),
        migrations.RemoveField(
            model_name="quotationtemplate",
            name="footer_notes",
        ),
        migrations.RemoveField(
            model_name="quotationtemplate",
            name="header_fields_config",
        ),
        migrations.RemoveField(
            model_name="quotationtemplate",
            name="layout_config",
        ),
        migrations.AlterField(
            model_name="quotation",
            name="grand_total",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="notes",
            field=models.TextField(blank=True, help_text="Additional notes"),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="shipping_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("sent", "Sent"),
                    ("accepted", "Accepted"),
                    ("declined", "Declined"),
                    ("expired", "Expired"),
                ],
                default="draft",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="terms",
            field=models.TextField(blank=True, help_text="Terms and conditions"),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="total_discount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="total_tax",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="quotationitem",
            name="quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="quotationitem",
            name="unit_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="quotationtemplate",
            name="name",
            field=models.CharField(
                default="Default Quotation",
                help_text="Template name (e.g., 'Professional Quotation', 'Service Quote')",
                max_length=200,
            ),
        ),
    ]
