# Generated by Django 4.2.7 on 2025-07-25 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
        ("quotations", "0006_remove_layout_config_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotation",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quotations",
                to="clients.client",
            ),
        ),
    ]
