# Generated by Django 4.2.7 on 2025-07-25 19:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotations', '0007_alter_quotation_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='quotation_number',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='quotation',
            unique_together={('user', 'quotation_number')},
        ),
    ]
