# Generated by Django 4.2.7 on 2025-07-25 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_merge_20250709_1603'),
        ('quotations', '0008_alter_quotation_quotation_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='conversion_date',
            field=models.DateTimeField(blank=True, help_text='Date when quotation was converted to invoice', null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='converted_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_quotation', to='invoices.invoice'),
        ),
    ]
