# Generated by Django 4.2.7 on 2025-07-04 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Waybill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waybill_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('waybill_date', models.DateField(auto_now_add=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('custom_data', models.JSONField(default=dict, help_text='Custom field values based on template')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WaybillFieldTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Text Input'), ('textarea', 'Textarea'), ('number', 'Number'), ('date', 'Date'), ('email', 'Email'), ('phone', 'Phone'), ('select', 'Dropdown'), ('checkbox', 'Checkbox'), ('section', 'Section Header')], max_length=20)),
                ('options', models.JSONField(default=dict, help_text='Field options (for select, etc.)')),
                ('is_required', models.BooleanField(default=False)),
                ('placeholder', models.CharField(blank=True, max_length=200)),
                ('help_text', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WaybillTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Template name (e.g., 'Shipping Waybill', 'Delivery Note')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of this template')),
                ('primary_color', models.CharField(default='#FF5900', help_text='Primary color (hex code)', max_length=7)),
                ('secondary_color', models.CharField(default='#f8f9fa', help_text='Secondary color (hex code)', max_length=7)),
                ('text_color', models.CharField(default='#333333', help_text='Text color (hex code)', max_length=7)),
                ('custom_fields', models.JSONField(default=dict, help_text='Custom field definitions')),
                ('table_columns', models.JSONField(default=list, help_text='Custom table column definitions')),
                ('show_company_logo', models.BooleanField(default=True)),
                ('show_company_details', models.BooleanField(default=True)),
                ('show_bank_details', models.BooleanField(default=False)),
                ('show_signature', models.BooleanField(default=True)),
                ('document_title', models.CharField(default='WAYBILL', help_text='Document title to display', max_length=100)),
                ('number_prefix', models.CharField(default='WB', help_text='Document number prefix', max_length=10)),
                ('is_default', models.BooleanField(default=False, help_text='Use as default template')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waybill_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='WaybillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_data', models.JSONField(default=dict, help_text='Item field values based on template columns')),
                ('row_order', models.PositiveIntegerField(default=0)),
                ('waybill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='waybills.waybill')),
            ],
            options={
                'ordering': ['row_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='waybill',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waybills', to='waybills.waybilltemplate'),
        ),
        migrations.AddField(
            model_name='waybill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waybills', to=settings.AUTH_USER_MODEL),
        ),
    ]
