# Generated by Django 4.2.7 on 2025-07-05 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='waybill',
            index=models.Index(fields=['user', '-created_at'], name='waybills_wa_user_id_20aeed_idx'),
        ),
        migrations.AddIndex(
            model_name='waybill',
            index=models.Index(fields=['waybill_number'], name='waybills_wa_waybill_a5a569_idx'),
        ),
        migrations.AddIndex(
            model_name='waybill',
            index=models.Index(fields=['status'], name='waybills_wa_status_7609e7_idx'),
        ),
        migrations.AddIndex(
            model_name='waybill',
            index=models.Index(fields=['waybill_date'], name='waybills_wa_waybill_fdce1f_idx'),
        ),
        migrations.AddIndex(
            model_name='waybill',
            index=models.Index(fields=['template', 'user'], name='waybills_wa_templat_ca3356_idx'),
        ),
    ]
