# Generated by Django 4.2.7 on 2025-07-09 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0002_add_performance_indexes'),
        ('waybills', '0002_update_waybill_status_choices'),
    ]

    operations = [
    ]
