# Generated by Django 4.2.7 on 2025-07-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0002_alter_invoice_due_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceitem",
            name="product_service",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="description",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
