# Generated by Django 4.2.7 on 2025-07-05 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0005_add_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Invoice', help_text="Template name (e.g., 'Professional Invoice', 'Service Invoice')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of this template')),
                ('primary_color', models.CharField(default='#FF5900', help_text='Primary color (hex code)', max_length=7)),
                ('secondary_color', models.CharField(default='#f8f9fa', help_text='Secondary color (hex code)', max_length=7)),
                ('text_color', models.CharField(default='#333333', help_text='Text color (hex code)', max_length=7)),
                ('accent_color', models.CharField(default='#e9ecef', help_text='Accent color for borders and highlights (hex code)', max_length=7)),
                ('show_company_logo', models.BooleanField(default=True)),
                ('show_company_details', models.BooleanField(default=True)),
                ('show_bank_details', models.BooleanField(default=True)),
                ('show_signature', models.BooleanField(default=True)),
                ('document_title', models.CharField(default='INVOICE', help_text='Document title to display', max_length=100)),
                ('number_prefix', models.CharField(default='INV', help_text='Invoice number prefix', max_length=10)),
                ('default_payment_terms', models.TextField(blank=True, default='Payment due within 30 days', help_text='Default payment terms for new invoices')),
                ('footer_text', models.TextField(blank=True, help_text='Footer text to display on invoices')),
                ('is_default', models.BooleanField(default=False, help_text='Use as default template')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='invoices.invoicetemplate'),
        ),
    ]
