# Generated by Django 4.2.7 on 2025-07-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_invoicetemplate_invoice_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('delivered', 'Delivered')], default='unpaid', max_length=15),
        ),
    ]
