# Generated by Django 4.2.7 on 2025-07-09 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_update_status_choices'),
        ('invoices', '0007_alter_invoice_status'),
    ]

    operations = [
    ]
