# Generated by Django 4.2.7 on 2025-07-31 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("income", "Income"), ("expense", "Expense")],
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="₦", max_length=10)),
                (
                    "tax",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=8, null=True
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=8, null=True
                    ),
                ),
                (
                    "net_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "source_app",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Entry"),
                            ("invoice", "Invoice"),
                            ("receipt", "Receipt"),
                            ("job_order", "Job Order"),
                            ("waybill", "Waybill"),
                            ("inventory", "Inventory"),
                            ("expense", "Expense Tracker"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "reference_model",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "transaction_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_reconciled", models.BooleanField(default=False)),
                ("is_void", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="core.companyprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounting_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-transaction_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "type"], name="accounting__user_id_d0d7bb_idx"
                    ),
                    models.Index(
                        fields=["company", "transaction_date"],
                        name="accounting__company_289ded_idx",
                    ),
                    models.Index(
                        fields=["source_app", "reference_id"],
                        name="accounting__source__adb3b2_idx",
                    ),
                    models.Index(
                        fields=["type", "transaction_date"],
                        name="accounting__type_e9c645_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Ledger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("month", models.IntegerField()),
                (
                    "total_income",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_expense",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "net_profit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "outstanding_invoices",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "pending_receipts",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledgers",
                        to="core.companyprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-month"],
                "indexes": [
                    models.Index(
                        fields=["company", "year", "month"],
                        name="accounting__company_02702a_idx",
                    )
                ],
                "unique_together": {("company", "year", "month")},
            },
        ),
        migrations.CreateModel(
            name="FinancialReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("income_statement", "Income Statement"),
                            ("balance_sheet", "Balance Sheet"),
                            ("cash_flow", "Cash Flow Statement"),
                            ("trial_balance", "Trial Balance"),
                            ("custom", "Custom Report"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("report_data", models.JSONField(default=dict)),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="reports/pdf/"),
                ),
                (
                    "excel_file",
                    models.FileField(blank=True, null=True, upload_to="reports/excel/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_reports",
                        to="core.companyprofile",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "report_type"],
                        name="accounting__company_440129_idx",
                    ),
                    models.Index(
                        fields=["start_date", "end_date"],
                        name="accounting__start_d_6ddaaa_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("account_number", models.CharField(max_length=20, unique=True)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("asset", "Asset"),
                            ("liability", "Liability"),
                            ("equity", "Equity"),
                            ("revenue", "Revenue"),
                            ("expense", "Expense"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "opening_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "current_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to="core.companyprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["account_number"],
                "indexes": [
                    models.Index(
                        fields=["company", "account_type"],
                        name="accounting__company_2e81bf_idx",
                    ),
                    models.Index(
                        fields=["account_number"], name="accounting__account_0a7a77_idx"
                    ),
                ],
            },
        ),
    ]
