# Generated by Django 4.2.7 on 2025-07-22 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("invoices", "0008_merge_20250709_1603"),
    ]

    operations = [
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receipt_no", models.CharField(max_length=20, unique=True)),
                ("client_name", models.CharField(max_length=255)),
                (
                    "amount_received",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("amount_in_words", models.CharField(max_length=500)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("bank_transfer", "Bank Transfer"),
                            ("cheque", "Cheque"),
                            ("card", "Card"),
                            ("mobile_money", "Mobile Money"),
                            ("other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("date_received", models.DateField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "balance_after_payment",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("custom_color", models.CharField(default="#000000", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipts",
                        to="invoices.invoice",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receipts_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
