# Generated by Django 4.2.7 on 2025-07-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="client_address",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="receipt",
            name="client_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
