# Generated by Django 4.2.7 on 2025-07-22 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0002_receipt_client_address_receipt_client_phone"),
        ("receipts", "0002_received_by_charfield"),
    ]

    operations = []
