# Generated by Django 4.2.7 on 2025-07-22 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("receipts", "0003_merge_20250722_1328"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="receipts_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
