# Generated by Django 4.2.7 on 2025-07-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_inventorycategory_inventoryproduct_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorycategory",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
