# Generated by Django 4.2.7 on 2025-07-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="joborder",
            name="tracking_id",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
